jobs:
  eslint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
        command: yarn lint
        name: Run eslint
version: 2.1
workflows:
  lint:
    jobs:
      - eslint
