version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint